//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Adapter.CustomerWS
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerProvider.CustomerRecord", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Customer.Pr" +
        "ovider")]
    [System.SerializableAttribute()]
    public partial class CustomerProviderCustomerRecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneHome
        {
            get
            {
                return this.PhoneHomeField;
            }
            set
            {
                this.PhoneHomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneMobile
        {
            get
            {
                return this.PhoneMobileField;
            }
            set
            {
                this.PhoneMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneWork
        {
            get
            {
                return this.PhoneWorkField;
            }
            set
            {
                this.PhoneWorkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/ccf/customer", ConfigurationName="Microsoft.Ccf.Adapter.CustomerWS.Customer")]
    public interface Customer
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/GetCustomerByID", ReplyAction="http://microsoft.com/ccf/customer/Customer/GetCustomerByIDResponse")]
        Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord GetCustomerByID(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/GetCustomerByGuid", ReplyAction="http://microsoft.com/ccf/customer/Customer/GetCustomerByGuidResponse")]
        Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord GetCustomerByGuid(string customerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/GetCustomerByEmail", ReplyAction="http://microsoft.com/ccf/customer/Customer/GetCustomerByEmailResponse")]
        Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord GetCustomerByEmail(string customerEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/GetCustomersByEmailID", ReplyAction="http://microsoft.com/ccf/customer/Customer/GetCustomersByEmailIDResponse")]
        Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord[] GetCustomersByEmailID(string emailID, int maxRecords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/GetCustomersByName", ReplyAction="http://microsoft.com/ccf/customer/Customer/GetCustomersByNameResponse")]
        Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord[] GetCustomersByName(string first, string last, int maxRecords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/GetCustomersByANI", ReplyAction="http://microsoft.com/ccf/customer/Customer/GetCustomersByANIResponse")]
        Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord[] GetCustomersByANI(string ani, int maxRecords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/customer/Customer/SetCustomer", ReplyAction="http://microsoft.com/ccf/customer/Customer/SetCustomerResponse")]
        void SetCustomer(Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord custRec);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CustomerChannel : Microsoft.Ccf.Adapter.CustomerWS.Customer, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CustomerClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Adapter.CustomerWS.Customer>, Microsoft.Ccf.Adapter.CustomerWS.Customer
    {
        
        public CustomerClient()
        {
        }
        
        public CustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord GetCustomerByID(string customerID)
        {
            return base.Channel.GetCustomerByID(customerID);
        }
        
        public Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord GetCustomerByGuid(string customerGuid)
        {
            return base.Channel.GetCustomerByGuid(customerGuid);
        }
        
        public Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord GetCustomerByEmail(string customerEmail)
        {
            return base.Channel.GetCustomerByEmail(customerEmail);
        }
        
        public Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord[] GetCustomersByEmailID(string emailID, int maxRecords)
        {
            return base.Channel.GetCustomersByEmailID(emailID, maxRecords);
        }
        
        public Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord[] GetCustomersByName(string first, string last, int maxRecords)
        {
            return base.Channel.GetCustomersByName(first, last, maxRecords);
        }
        
        public Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord[] GetCustomersByANI(string ani, int maxRecords)
        {
            return base.Channel.GetCustomersByANI(ani, maxRecords);
        }
        
        public void SetCustomer(Microsoft.Ccf.Adapter.CustomerWS.CustomerProviderCustomerRecord custRec)
        {
            base.Channel.SetCustomer(custRec);
        }
    }
}
