//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.HostedControlInterfaces.RegisterClient
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.ccf/RegisterClient/", ConfigurationName="Microsoft.Ccf.Samples.HostedControlInterfaces.RegisterClient.RegisterClient")]
    public interface RegisterClient
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.ccf/RegisterClient/RegisterClient/Register", ReplyAction="http://microsoft.ccf/RegisterClient/RegisterClient/RegisterResponse")]
        int Register(System.Guid clientID, int agentID, string ipAddress, string port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.ccf/RegisterClient/RegisterClient/Unregister", ReplyAction="http://microsoft.ccf/RegisterClient/RegisterClient/UnregisterResponse")]
        void Unregister(System.Guid clientID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RegisterClientChannel : Microsoft.Ccf.Samples.HostedControlInterfaces.RegisterClient.RegisterClient, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RegisterClientClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Samples.HostedControlInterfaces.RegisterClient.RegisterClient>, Microsoft.Ccf.Samples.HostedControlInterfaces.RegisterClient.RegisterClient
    {
        
        public RegisterClientClient()
        {
        }
        
        public RegisterClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RegisterClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RegisterClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RegisterClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int Register(System.Guid clientID, int agentID, string ipAddress, string port)
        {
            return base.Channel.Register(clientID, agentID, ipAddress, port);
        }
        
        public void Unregister(System.Guid clientID)
        {
            base.Channel.Unregister(clientID);
        }
    }
}
