//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentStatsProvider.AgentStatsRecord", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentRecord))]
    public partial class AgentStatsProviderAgentStatsRecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LoginTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StateTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCallTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LoginTimeStamp
        {
            get
            {
                return this.LoginTimeStampField;
            }
            set
            {
                this.LoginTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIPAddress
        {
            get
            {
                return this.SIPAddressField;
            }
            set
            {
                this.SIPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID
        {
            get
            {
                return this.StateIDField;
            }
            set
            {
                this.StateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StateTimeStamp
        {
            get
            {
                return this.StateTimeStampField;
            }
            set
            {
                this.StateTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCallTime
        {
            get
            {
                return this.TotalCallTimeField;
            }
            set
            {
                this.TotalCallTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCalls
        {
            get
            {
                return this.TotalCallsField;
            }
            set
            {
                this.TotalCallsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentStatsProvider.AgentRecord", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    [System.SerializableAttribute()]
    public partial class AgentStatsProviderAgentRecord : Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentStatsRecord
    {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Supervisor
        {
            get
            {
                return this.SupervisorField;
            }
            set
            {
                this.SupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentStatsProvider.SessionTransferRecord", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    [System.SerializableAttribute()]
    public partial class AgentStatsProviderSessionTransferRecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fromAgentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int toAgentIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fromAgentID
        {
            get
            {
                return this.fromAgentIDField;
            }
            set
            {
                this.fromAgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromPhoneNumber
        {
            get
            {
                return this.fromPhoneNumberField;
            }
            set
            {
                this.fromPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionInfo
        {
            get
            {
                return this.sessionInfoField;
            }
            set
            {
                this.sessionInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int toAgentID
        {
            get
            {
                return this.toAgentIDField;
            }
            set
            {
                this.toAgentIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/ccf/ContactCenter/AgentStats", ConfigurationName="Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentState")]
    public interface AgentState
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentInformation", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentInformationR" +
            "esponse")]
        Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentRecord GetAgentInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentInformationB" +
            "yDomainUser", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentInformationB" +
            "yDomainUserResponse")]
        Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentRecord GetAgentInformationByDomainUser(string domainUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/SetAgentState", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/SetAgentStateRespons" +
            "e")]
        void SetAgentState(int state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/AgentLogin", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/AgentLoginResponse")]
        int AgentLogin(string SIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/AgentLogin2", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/AgentLogin2Response")]
        int AgentLogin2(string SIP, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentStats", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentStatsRespons" +
            "e")]
        System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentStatsRecord> GetAgentStats(int agentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentIDFromPhoneN" +
            "umber", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentIDFromPhoneN" +
            "umberResponse")]
        int GetAgentIDFromPhoneNumber(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/SetSessionTransferIn" +
            "formation", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/SetSessionTransferIn" +
            "formationResponse")]
        void SetSessionTransferInformation(int toAgentID, string fromPhoneNumber, int fromAgentID, string sessionInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetSessionTransferIn" +
            "formation", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetSessionTransferIn" +
            "formationResponse")]
        System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderSessionTransferRecord> GetSessionTransferInformation(int toAgentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/SaveSessions", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/SaveSessionsResponse" +
            "")]
        void SaveSessions(int agentID, string sessionsState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetSavedSessions", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetSavedSessionsResp" +
            "onse")]
        string GetSavedSessions(int agentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentByDomainUser" +
            "Name", ReplyAction="http://microsoft.com/ccf/ContactCenter/AgentStats/AgentState/GetAgentByDomainUser" +
            "NameResponse")]
        string GetAgentByDomainUserName();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AgentStateChannel : Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentState, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AgentStateClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentState>, Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentState
    {
        
        public AgentStateClient()
        {
        }
        
        public AgentStateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AgentStateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AgentStateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AgentStateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentRecord GetAgentInformation()
        {
            return base.Channel.GetAgentInformation();
        }
        
        public Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentRecord GetAgentInformationByDomainUser(string domainUser)
        {
            return base.Channel.GetAgentInformationByDomainUser(domainUser);
        }
        
        public void SetAgentState(int state)
        {
            base.Channel.SetAgentState(state);
        }
        
        public int AgentLogin(string SIP)
        {
            return base.Channel.AgentLogin(SIP);
        }
        
        public int AgentLogin2(string SIP, string Phone)
        {
            return base.Channel.AgentLogin2(SIP, Phone);
        }
        
        public System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderAgentStatsRecord> GetAgentStats(int agentID)
        {
            return base.Channel.GetAgentStats(agentID);
        }
        
        public int GetAgentIDFromPhoneNumber(string phoneNumber)
        {
            return base.Channel.GetAgentIDFromPhoneNumber(phoneNumber);
        }
        
        public void SetSessionTransferInformation(int toAgentID, string fromPhoneNumber, int fromAgentID, string sessionInformation)
        {
            base.Channel.SetSessionTransferInformation(toAgentID, fromPhoneNumber, fromAgentID, sessionInformation);
        }
        
        public System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.AgentStats.AgentStatsProviderSessionTransferRecord> GetSessionTransferInformation(int toAgentID)
        {
            return base.Channel.GetSessionTransferInformation(toAgentID);
        }
        
        public void SaveSessions(int agentID, string sessionsState)
        {
            base.Channel.SaveSessions(agentID, sessionsState);
        }
        
        public string GetSavedSessions(int agentID)
        {
            return base.Channel.GetSavedSessions(agentID);
        }
        
        public string GetAgentByDomainUserName()
        {
            return base.Channel.GetAgentByDomainUserName();
        }
    }
}
