//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactCenterStatisticsProvider.CallCenterStats", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    [System.SerializableAttribute()]
    public partial class ContactCenterStatisticsProviderCallCenterStats : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long avgWaitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long callsWaitingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long longestWaitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tickerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long avgWait
        {
            get
            {
                return this.avgWaitField;
            }
            set
            {
                this.avgWaitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long callsWaiting
        {
            get
            {
                return this.callsWaitingField;
            }
            set
            {
                this.callsWaitingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long longestWait
        {
            get
            {
                return this.longestWaitField;
            }
            set
            {
                this.longestWaitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ticker
        {
            get
            {
                return this.tickerField;
            }
            set
            {
                this.tickerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/ccf/ContactCenter/ContactCenterStatistics", ConfigurationName="Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics.ContactCenterStati" +
        "stics")]
    public interface ContactCenterStatistics
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/ContactCenterStatistics/ContactCenterStati" +
            "stics/GetContactCenterStatistics", ReplyAction="http://microsoft.com/ccf/ContactCenter/ContactCenterStatistics/ContactCenterStati" +
            "stics/GetContactCenterStatisticsResponse")]
        Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics.ContactCenterStatisticsProviderCallCenterStats GetContactCenterStatistics();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ContactCenterStatisticsChannel : Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics.ContactCenterStatistics, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ContactCenterStatisticsClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics.ContactCenterStatistics>, Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics.ContactCenterStatistics
    {
        
        public ContactCenterStatisticsClient()
        {
        }
        
        public ContactCenterStatisticsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ContactCenterStatisticsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ContactCenterStatisticsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ContactCenterStatisticsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Microsoft.Ccf.Samples.Csr.AgentDesktop.ContactCenterStatistics.ContactCenterStatisticsProviderCallCenterStats GetContactCenterStatistics()
        {
            return base.Channel.GetContactCenterStatistics();
        }
    }
}
