//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupProvider.LookupEntry", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    [System.SerializableAttribute()]
    public partial class LookupProviderLookupEntry : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupProvider.Channel", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    public enum LookupProviderChannel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Voice = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessaging = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteAssistance = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupProvider.PresenceState", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    public enum LookupProviderPresenceState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOut = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unused = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnCallActive = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnCallHold = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallWrapup = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Away = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assisting = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Busy = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/ccf/ContactCenter/Lookup", ConfigurationName="Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.Lookup")]
    public interface Lookup
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/GetSkills", ReplyAction="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/GetSkillsResponse")]
        System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderLookupEntry> GetSkills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/GetChannels", ReplyAction="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/GetChannelsResponse")]
        System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderLookupEntry> GetChannels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/GetPresenceStates", ReplyAction="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/GetPresenceStatesResponse")]
        System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderLookupEntry> GetPresenceStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/ChannelEnumeration", ReplyAction="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/ChannelEnumerationResponse")]
        Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderChannel ChannelEnumeration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/PresenceStateEnumeration", ReplyAction="http://microsoft.com/ccf/ContactCenter/Lookup/Lookup/PresenceStateEnumerationResp" +
            "onse")]
        Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderPresenceState PresenceStateEnumeration();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LookupChannel : Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.Lookup, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LookupClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.Lookup>, Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.Lookup
    {
        
        public LookupClient()
        {
        }
        
        public LookupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LookupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LookupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LookupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderLookupEntry> GetSkills()
        {
            return base.Channel.GetSkills();
        }
        
        public System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderLookupEntry> GetChannels()
        {
            return base.Channel.GetChannels();
        }
        
        public System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderLookupEntry> GetPresenceStates()
        {
            return base.Channel.GetPresenceStates();
        }
        
        public Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderChannel ChannelEnumeration()
        {
            return base.Channel.ChannelEnumeration();
        }
        
        public Microsoft.Ccf.Samples.Csr.AgentDesktop.Lookup.LookupProviderPresenceState PresenceStateEnumeration()
        {
            return base.Channel.PresenceStateEnumeration();
        }
    }
}
