//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoutingProvider.AgentContact", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Ccf.Csr.WebServices.Providers.C" +
        "ontactCenter")]
    [System.SerializableAttribute()]
    public partial class RoutingProviderAgentContact : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIPAddressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIPAddress
        {
            get
            {
                return this.SIPAddressField;
            }
            set
            {
                this.SIPAddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/ccf/ContactCenter/Routing", ConfigurationName="Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting.Routing")]
    public interface Routing
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/ccf/ContactCenter/Routing/Routing/GetSkillContacts", ReplyAction="http://microsoft.com/ccf/ContactCenter/Routing/Routing/GetSkillContactsResponse")]
        System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting.RoutingProviderAgentContact> GetSkillContacts(int skill, int channel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RoutingChannel : Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting.Routing, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RoutingClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting.Routing>, Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting.Routing
    {
        
        public RoutingClient()
        {
        }
        
        public RoutingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RoutingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RoutingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RoutingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ComponentModel.BindingList<Microsoft.Ccf.Samples.Csr.AgentDesktop.SkillsRouting.RoutingProviderAgentContact> GetSkillContacts(int skill, int channel)
        {
            return base.Channel.GetSkillContacts(skill, channel);
        }
    }
}
