//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.Csr.AgentDesktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Ccf.Samples.Csr.AgentDesktop.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_CANCEL_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_CANCEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing address book..
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_ERR_INITIALIZING_ADDR_BOOK {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_ERR_INITIALIZING_ADDR_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading address book..
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_ERR_READING_ADDR_BOOK {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_ERR_READING_ADDR_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_FIND_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_FIND_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name or first letters of a name to find.  Hold the mouse over a name for details..
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_LABEL1_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_LABEL1_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no address to dial..
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_MSG_NO_ADDR {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_MSG_NO_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select an address to dial..
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_MSG_SELECT_ADDR {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_MSG_SELECT_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_NAME_TO_FIND {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_NAME_TO_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dial.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_OK_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_OK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_PHONE_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_PHONE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Book.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_DEPT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_EMAIL {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_LOCATION {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_PHONE {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_TITLE {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_TOOLTIP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AGENT_DESKTOP_ADDR_BOOK_DLG_USERNAME_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_ADDR_BOOK_DLG_USERNAME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address Book.
        /// </summary>
        internal static string AGENT_DESKTOP_GET_NUMBER_ADDR_BOOK_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_GET_NUMBER_ADDR_BOOK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string AGENT_DESKTOP_GET_NUMBER_CANCEL_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_GET_NUMBER_CANCEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem reading address book..
        /// </summary>
        internal static string AGENT_DESKTOP_GET_NUMBER_ERR_READING_ADDR_BOOK {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_GET_NUMBER_ERR_READING_ADDR_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call:.
        /// </summary>
        internal static string AGENT_DESKTOP_GET_NUMBER_LABEL1_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_GET_NUMBER_LABEL1_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dial.
        /// </summary>
        internal static string AGENT_DESKTOP_GET_NUMBER_OK_TEXT {
            get {
                return ResourceManager.GetString("AGENT_DESKTOP_GET_NUMBER_OK_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AgentDesktop {
            get {
                object obj = ResourceManager.GetObject("AgentDesktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Desktop.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Customer Care Framework.
        /// </summary>
        internal static string CCF_ABOUT_CONTACT_CENTER_FRAMEWORK {
            get {
                return ResourceManager.GetString("CCF_ABOUT_CONTACT_CENTER_FRAMEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2000-2007 Microsoft Corporation.
        /// </summary>
        internal static string CCF_ABOUT_COPYRIGHT {
            get {
                return ResourceManager.GetString("CCF_ABOUT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Version: .
        /// </summary>
        internal static string CCF_ABOUT_DOTNET_VERSION {
            get {
                return ResourceManager.GetString("CCF_ABOUT_DOTNET_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 3.0.
        /// </summary>
        internal static string CCF_ABOUT_VERSION {
            get {
                return ResourceManager.GetString("CCF_ABOUT_VERSION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ccf_splash_screen_2008 {
            get {
                object obj = ResourceManager.GetObject("ccf_splash_screen_2008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server does not exist.
        /// </summary>
        internal static string COMMON_ERR_SQL_CONNECTION {
            get {
                return ResourceManager.GetString("COMMON_ERR_SQL_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the web server.
        /// </summary>
        internal static string COMMON_MSG_IIS_ERROR {
            get {
                return ResourceManager.GetString("COMMON_MSG_IIS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Desktop Version: .
        /// </summary>
        internal static string DESKTOP_AGENT_DESKTOP_VERSION {
            get {
                return ResourceManager.GetString("DESKTOP_AGENT_DESKTOP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Answer.
        /// </summary>
        internal static string DESKTOP_ANSWER_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_ANSWER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve saved sessions..
        /// </summary>
        internal static string DESKTOP_APP_RESTORE_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_APP_RESTORE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the hosted application states..
        /// </summary>
        internal static string DESKTOP_APP_SAVE_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_APP_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create hosted applications.
        ///
        ///The application may now exit..
        /// </summary>
        internal static string DESKTOP_APPCREATE_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_APPCREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicat&amp;ions.
        /// </summary>
        internal static string DESKTOP_APPLICATIONS_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_APPLICATIONS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start an Application.
        /// </summary>
        internal static string DESKTOP_APPLICATIONS_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_APPLICATIONS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start application:.
        /// </summary>
        internal static string DESKTOP_APPSTART_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_APPSTART_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in displaying the CCF About dialog box..
        /// </summary>
        internal static string DESKTOP_CCF_ABOUT_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_CCF_ABOUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close this session now?.
        /// </summary>
        internal static string DESKTOP_CLOSE_AFTER_TRANSFER {
            get {
                return ResourceManager.GetString("DESKTOP_CLOSE_AFTER_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the current session.
        /// </summary>
        internal static string DESKTOP_CLOSE_SESSION_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_CLOSE_SESSION_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Conference.
        /// </summary>
        internal static string DESKTOP_CONFERENCE_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_CONFERENCE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTI debug is enabled.
        /// </summary>
        internal static string DESKTOP_CTI_DEBUG_ENABLED {
            get {
                return ResourceManager.GetString("DESKTOP_CTI_DEBUG_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCF Databases Version: .
        /// </summary>
        internal static string DESKTOP_DATABASES_VERSION {
            get {
                return ResourceManager.GetString("DESKTOP_DATABASES_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The versions of Agent Desktop and the CCF Databases are not same..
        /// </summary>
        internal static string DESKTOP_DB_VERSION_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_DB_VERSION_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dial.
        /// </summary>
        internal static string DESKTOP_DIAL_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_DIAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to launch the Dynamic Hosted Application?.
        /// </summary>
        internal static string DESKTOP_DYNAMIC_APP_LAUNCH_CONFIRMATION_MSG {
            get {
                return ResourceManager.GetString("DESKTOP_DYNAMIC_APP_LAUNCH_CONFIRMATION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Applications..
        /// </summary>
        internal static string DESKTOP_DYNAMIC_APPS {
            get {
                return ResourceManager.GetString("DESKTOP_DYNAMIC_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a Dynamic Application..
        /// </summary>
        internal static string DESKTOP_DYNAMIC_APPS_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_DYNAMIC_APPS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get applications information from the hosted applications..
        /// </summary>
        internal static string DESKTOP_ERR_APP_DETAILS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_APP_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the icon list of applications from hosted applications due to an error in Agent desktop..
        /// </summary>
        internal static string DESKTOP_ERR_BUILDAPPIMAGELIST {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_BUILDAPPIMAGELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in changing the session through current session..
        /// </summary>
        internal static string DESKTOP_ERR_CHANGING_SESSION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_CHANGING_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while clicking the toolbar button..
        /// </summary>
        internal static string DESKTOP_ERR_CLICKING_TOOLBAR_BUTTON {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_CLICKING_TOOLBAR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while making a conference call.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_CONFERENCING_CALL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_CONFERENCING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this hosted application.Please contact the system administrator..
        /// </summary>
        internal static string DESKTOP_ERR_COULDNOT_FIND_APPLICATION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_COULDNOT_FIND_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string DESKTOP_ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A possibly fatal error has occurred.  The application may now exit..
        /// </summary>
        internal static string DESKTOP_ERR_FATAL_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_FATAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.  The user login or database settings may be incorrect or the database may not be reachable..
        /// </summary>
        internal static string DESKTOP_ERR_FATAL_UNABLE_LOG {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_FATAL_UNABLE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to hang up the call.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_HANGUP_PHONE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_HANGUP_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in call event..
        /// </summary>
        internal static string DESKTOP_ERR_IN_CALL_EVENT {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_IN_CALL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading Desktop..
        /// </summary>
        internal static string DESKTOP_ERR_IN_LOAD {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_IN_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Session Explorer..
        /// </summary>
        internal static string DESKTOP_ERR_INIT_SESSION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_INIT_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while initializing telephony component..
        /// </summary>
        internal static string DESKTOP_ERR_INIT_TELEPHONY {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_INIT_TELEPHONY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading applications. Desktop will now close..
        /// </summary>
        internal static string DESKTOP_ERR_LOADING_APPLICATIONS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_LOADING_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading the session into the current session {0}.
        /// </summary>
        internal static string DESKTOP_ERR_LOADING_SESSION_INTO_CS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_LOADING_SESSION_INTO_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Customer Lookup from Call event..
        /// </summary>
        internal static string DESKTOP_ERR_LOOKUP_CALL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_LOOKUP_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to make a call.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_MAKING_CALL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_MAKING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify the Agent&apos;s status..
        /// </summary>
        internal static string DESKTOP_ERR_MODIFY_STATUS_MENU {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_MODIFY_STATUS_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to put the call on hold.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_PLACING_HOLD {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_PLACING_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while pre-filtering messages..
        /// </summary>
        internal static string DESKTOP_ERR_PREFILTERING_MSG {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_PREFILTERING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot receive a call if telephony objects are not configured..
        /// </summary>
        internal static string DESKTOP_ERR_RECD_CALL_EVENT {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_RECD_CALL_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance disabled.
        /// </summary>
        internal static string DESKTOP_ERR_REQUEST_ASSISTANCE_CAPTION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_REQUEST_ASSISTANCE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not enabled for instant messaging. You will not be able to request assistance..
        /// </summary>
        internal static string DESKTOP_ERR_REQUEST_ASSISTANCE_MESSAGE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_REQUEST_ASSISTANCE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the requested assistance details..
        /// </summary>
        internal static string DESKTOP_ERR_REQUESTASSISTANCE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_REQUESTASSISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving agent identifier given the agent phone number..
        /// </summary>
        internal static string DESKTOP_ERR_RETRIEVING_AGENT_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_RETRIEVING_AGENT_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while initializing RTC component.  You will not be able to use Instant Messaging..
        /// </summary>
        internal static string DESKTOP_ERR_RTC {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_RTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTC is disabled because of a conflict with TAPI.
        ///You can use CTI remoting with TAPI or
        ///Use a telephony standard besides TAPI or not use RTC..
        /// </summary>
        internal static string DESKTOP_ERR_RTC_TAPI_CONFLICT {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_RTC_TAPI_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the application context..
        /// </summary>
        internal static string DESKTOP_ERR_SETTING_CONTEXT_APP {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_SETTING_CONTEXT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set up the menu..
        /// </summary>
        internal static string DESKTOP_ERR_SETUP_MENU {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_SETUP_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to take the call off hold.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_TAKING_CALLOFF_HOLD {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_TAKING_CALLOFF_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer the call.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_TRANSFERRING_CALL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_TRANSFERRING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error transferring the session..
        /// </summary>
        internal static string DESKTOP_ERR_TRANSFERRING_SESSION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_TRANSFERRING_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure a phone..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_CONFIGURE_PHONE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_CONFIGURE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to SQL database..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_CONNECT_SQL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_CONNECT_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to establish connection to telephony component..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_ESTABLISH_CONNECTION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_ESTABLISH_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find hosted applications.
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_HOSTEDAPP {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_HOSTEDAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login - make sure your domain\\user name is correctly configured in the system.
        ///
        ///Application will exit now..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_LOGIN {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to marshal the call event to main thread..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_MARSHALL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_MARSHALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTC must be enabled before requesting assistance..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_REQUEST_ASSISTANCE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_REQUEST_ASSISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reset customer information..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_RESET_CUSTINFO {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_RESET_CUSTINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set presence value.
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_SET_PRESENCE_VALUE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_SET_PRESENCE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set status to.
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_SET_STATUS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_SET_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the options settings..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_TO_READ_OPTIONS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_TO_READ_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in retrieving the workflow data.  Please try again..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_TO_RETRIEVE_WORKFLOW_DATA {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_TO_RETRIEVE_WORKFLOW_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start application.
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_TOSTART_APPLICATION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_TOSTART_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start web services..
        /// </summary>
        internal static string DESKTOP_ERR_UNABLE_WEBSERVICE {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UNABLE_WEBSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while updating the current session of the active application:{0}.
        /// </summary>
        internal static string DESKTOP_ERR_UPDATING_CS_WITH_CURR_APP {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UPDATING_CS_WITH_CURR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating current session on Session Closed:{0}.
        /// </summary>
        internal static string DESKTOP_ERR_UPDATING_CURRENTSESSION {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UPDATING_CURRENTSESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while updating hosted application/current session :{0}.
        /// </summary>
        internal static string DESKTOP_ERR_UPDATING_HOSTED_APP_OR_CS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UPDATING_HOSTED_APP_OR_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the hosted application&apos;s state..
        /// </summary>
        internal static string DESKTOP_ERR_UPDATING_HOSTEDAPPS {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_UPDATING_HOSTEDAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other reasons for this error are that the database could not be reached/nor the web services are not running..
        /// </summary>
        internal static string DESKTOP_EXPLAIN_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_EXPLAIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference.
        /// </summary>
        internal static string DESKTOP_GETNUMBER_CONFERENCE {
            get {
                return ResourceManager.GetString("DESKTOP_GETNUMBER_CONFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial.
        /// </summary>
        internal static string DESKTOP_GETNUMBER_DIAL {
            get {
                return ResourceManager.GetString("DESKTOP_GETNUMBER_DIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hangup.
        /// </summary>
        internal static string DESKTOP_HANGUP_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_HANGUP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string DESKTOP_HELP_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help - About Customer Care Framework.
        /// </summary>
        internal static string DESKTOP_HELP_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_HELP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hold.
        /// </summary>
        internal static string DESKTOP_HOLD_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_HOLD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the web server.  Please verify that you can connect to the web server..
        /// </summary>
        internal static string DESKTOP_IIS_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_IIS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentdesktop exited..
        /// </summary>
        internal static string DESKTOP_INFO_AGENT_DESKTOP_EXITED {
            get {
                return ResourceManager.GetString("DESKTOP_INFO_AGENT_DESKTOP_EXITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been on a call for {0} minute.
        /// </summary>
        internal static string DESKTOP_INFO_CALL_LENGTH {
            get {
                return ResourceManager.GetString("DESKTOP_INFO_CALL_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been on a call for {0} minutes.
        /// </summary>
        internal static string DESKTOP_INFO_CALL_LENGTH_PLURAL {
            get {
                return ResourceManager.GetString("DESKTOP_INFO_CALL_LENGTH_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Current Call..
        /// </summary>
        internal static string DESKTOP_INFO_NO_CURRENT_CALL {
            get {
                return ResourceManager.GetString("DESKTOP_INFO_NO_CURRENT_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling.
        /// </summary>
        internal static string DESKTOP_INFOTEXT_CALLING {
            get {
                return ResourceManager.GetString("DESKTOP_INFOTEXT_CALLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the Non-Hosted Applications..
        /// </summary>
        internal static string DESKTOP_LOADNONHOSTEDAPP_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_LOADNONHOSTEDAPP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Look Up.
        /// </summary>
        internal static string DESKTOP_LOOKUP_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_LOOKUP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up a customer record.
        /// </summary>
        internal static string DESKTOP_LOOKUP_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_LOOKUP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About Customer Care Framework.
        /// </summary>
        internal static string DESKTOP_MENU_ITEM_TEXT_ABOUT_CONTACT_CENTER_FRAMEWORK {
            get {
                return ResourceManager.GetString("DESKTOP_MENU_ITEM_TEXT_ABOUT_CONTACT_CENTER_FRAMEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care - Agent Desktop.
        /// </summary>
        internal static string DESKTOP_MESSAGE_BOX_CAPTION {
            get {
                return ResourceManager.GetString("DESKTOP_MESSAGE_BOX_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify the phone menu..
        /// </summary>
        internal static string DESKTOP_MODIFY_PHONE_MENU {
            get {
                return ResourceManager.GetString("DESKTOP_MODIFY_PHONE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Desktop.
        /// </summary>
        internal static string DESKTOP_MODULE_NAME {
            get {
                return ResourceManager.GetString("DESKTOP_MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is already running..
        /// </summary>
        internal static string DESKTOP_MSG_ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called by.
        /// </summary>
        internal static string DESKTOP_MSG_CALLEDBY {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_CALLEDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls.
        /// </summary>
        internal static string DESKTOP_MSG_CALLS {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_CALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On call with.
        /// </summary>
        internal static string DESKTOP_MSG_CALLWITH {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_CALLWITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login - One of the login details is empty. Please give all the details and try again..
        /// </summary>
        internal static string DESKTOP_MSG_EMPTY_LOGIN_DETAILS {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_EMPTY_LOGIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login - make sure your login details are correct and try again. Contact administrator if the problem persists..
        /// </summary>
        internal static string DESKTOP_MSG_INVALID_LOGIN_DETAILS {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_INVALID_LOGIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error while login to the server. Please try after sometime..
        /// </summary>
        internal static string DESKTOP_MSG_LOGIN_FAILURE_ {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_LOGIN_FAILURE ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no configured phone to use..
        /// </summary>
        internal static string DESKTOP_MSG_NO_CONFIGURED_PHONE {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_NO_CONFIGURED_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        internal static string DESKTOP_MSG_ONHOLD {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_ONHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out going.
        /// </summary>
        internal static string DESKTOP_MSG_OUTGOING {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_OUTGOING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringing.
        /// </summary>
        internal static string DESKTOP_MSG_RINGING {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_RINGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server can not be found..
        /// </summary>
        internal static string DESKTOP_MSG_SQL_EXIST {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_SQL_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentdesktop starting....
        /// </summary>
        internal static string DESKTOP_MSG_STARTING {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting IM conversation with.
        /// </summary>
        internal static string DESKTOP_MSG_STARTING_IM {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_STARTING_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a conference call.  Please try again..
        /// </summary>
        internal static string DESKTOP_MSG_UNABLE_CREATE_CONF {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_UNABLE_CREATE_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find assistance for.
        /// </summary>
        internal static string DESKTOP_MSG_UNABLE_FIND_ASSISTANCE {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_UNABLE_FIND_ASSISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on.
        /// </summary>
        internal static string DESKTOP_MSG_YOU_ARE_ON {
            get {
                return ResourceManager.GetString("DESKTOP_MSG_YOU_ARE_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer .
        /// </summary>
        internal static string DESKTOP_NEW_CUSTOMER {
            get {
                return ResourceManager.GetString("DESKTOP_NEW_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Phone.
        /// </summary>
        internal static string DESKTOP_PHONE_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_PHONE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make and Handle Calls.
        /// </summary>
        internal static string DESKTOP_PHONE_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_PHONE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Assistance.
        /// </summary>
        internal static string DESKTOP_REQUEST_ASSISTANCE_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_REQUEST_ASSISTANCE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request assistance with a specified subject..
        /// </summary>
        internal static string DESKTOP_REQUEST_ASSISTANCE_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_REQUEST_ASSISTANCE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status:.
        /// </summary>
        internal static string DESKTOP_STATUS_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_STATUS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows and sets your current status.
        /// </summary>
        internal static string DESKTOP_STATUS_TOOLTIP {
            get {
                return ResourceManager.GetString("DESKTOP_STATUS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the application details from the selected tab..
        /// </summary>
        internal static string DESKTOP_TABAPP_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_TABAPP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to display the tab page of the selected application..
        /// </summary>
        internal static string DESKTOP_TABFOCUS_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_TABFOCUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string DESKTOP_TIMER_TICK_INFO_EXCEPTION {
            get {
                return ResourceManager.GetString("DESKTOP_TIMER_TICK_INFO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Transfer.
        /// </summary>
        internal static string DESKTOP_TRANSFER_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_TRANSFER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unhold.
        /// </summary>
        internal static string DESKTOP_UNHOLD_TEXT {
            get {
                return ResourceManager.GetString("DESKTOP_UNHOLD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DESKTOP_UNKNOWN_VERSION {
            get {
                return ResourceManager.GetString("DESKTOP_UNKNOWN_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the Hosted Application state..
        /// </summary>
        internal static string DESKTOP_UPDATEHOSTEDAPP_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_UPDATEHOSTEDAPP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The versions of CCF databases and the web services could not be retrieved..
        /// </summary>
        internal static string DESKTOP_VERSIONS_RETRIEVAL_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_VERSIONS_RETRIEVAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCF Web Services Version: .
        /// </summary>
        internal static string DESKTOP_WEB_SERVICES_VERSION {
            get {
                return ResourceManager.GetString("DESKTOP_WEB_SERVICES_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The versions of Agent Desktop and the CCF Web Services are not same..
        /// </summary>
        internal static string DESKTOP_WS_VERSION_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("DESKTOP_WS_VERSION_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LOOKUP_DLG_ADDRESS {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string LOOKUP_DLG_BTN_NEW {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_BTN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string LOOKUP_DLG_CANCEL {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMsg.
        /// </summary>
        internal static string LOOKUP_DLG_ERROR_MSG {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string LOOKUP_DLG_FIRST {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        internal static string LOOKUP_DLG_HOME_PHONE {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_HOME_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ustomer ID:.
        /// </summary>
        internal static string LOOKUP_DLG_LABEL1 {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LABEL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string LOOKUP_DLG_LABEL4 {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LABEL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las&amp;t Name:.
        /// </summary>
        internal static string LOOKUP_DLG_LABEL7 {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LABEL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LOOKUP_DLG_LAST {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;First Name:.
        /// </summary>
        internal static string LOOKUP_DLG_LBEL8 {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LBEL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string LOOKUP_DLG_LBL5 {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LBL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;hone Number:.
        /// </summary>
        internal static string LOOKUP_DLG_LBL6 {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LBL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &amp;Lookup ID.
        /// </summary>
        internal static string LOOKUP_DLG_LOOKUP_ID {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LOOKUP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup N&amp;ame.
        /// </summary>
        internal static string LOOKUP_DLG_LOOKUP_NAME {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LOOKUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup &amp;Phone.
        /// </summary>
        internal static string LOOKUP_DLG_LOOKUP_PHONE {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_LOOKUP_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need both a first and last name or at least both a partial first and last name..
        /// </summary>
        internal static string LOOKUP_DLG_NEED_BOTH_NAMES {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_NEED_BOTH_NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no customer record selected..
        /// </summary>
        internal static string LOOKUP_DLG_NO_RECORD_SELECTED {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_NO_RECORD_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select.
        /// </summary>
        internal static string LOOKUP_DLG_SELECT {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Customer.
        /// </summary>
        internal static string LOOKUP_DLG_TEXT {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified customer..
        /// </summary>
        internal static string LOOKUP_DLG_UNABLE_CUST_ID {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_UNABLE_CUST_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a customer with the specified name..
        /// </summary>
        internal static string LOOKUP_DLG_UNABLE_CUST_NAME {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_UNABLE_CUST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a customer with the specified phone number..
        /// </summary>
        internal static string LOOKUP_DLG_UNABLE_CUST_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_UNABLE_CUST_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the customer record..
        /// </summary>
        internal static string LOOKUP_DLG_UNABLE_CUST_RECORD {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_UNABLE_CUST_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string LOOKUP_DLG_WORK_PHONE {
            get {
                return ResourceManager.GetString("LOOKUP_DLG_WORK_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string SELECT_CALL_DLG_BTN_CANCEL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SELECT_CALL_DLG_BTN_OK {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which call to use:.
        /// </summary>
        internal static string SELECT_CALL_DLG_LABEL1 {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_LABEL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties.
        /// </summary>
        internal static string SELECT_CALL_DLG_PARTIES_COL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_PARTIES_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any row in the list..
        /// </summary>
        internal static string SELECT_CALL_DLG_SELECT_A_CALL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_SELECT_A_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string SELECT_CALL_DLG_STARTED_COL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_STARTED_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SELECT_CALL_DLG_STATE_COL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_STATE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which Call.
        /// </summary>
        internal static string SELECT_CALL_DLG_TEXT {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Session.
        /// </summary>
        internal static string SESSION_EXPLORER_CLOSE_SESSION {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_CLOSE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to display/hide Help for Session Explorer..
        /// </summary>
        internal static string SESSION_EXPLORER_ERR_DISPLAYING_HELP {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_ERR_DISPLAYING_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SESSION_EXPLORER_LABEL_HELP_ICON_TEXT {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_LABEL_HELP_ICON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        internal static string SESSION_EXPLORER_LABEL_SORT_BY_TEXT {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_LABEL_SORT_BY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Explorer.
        /// </summary>
        internal static string SESSION_EXPLORER_MODULE_NAME {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0} Session(s).
        /// </summary>
        internal static string SESSION_EXPLORER_SESSIONS_COUNT {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_SESSIONS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking a session will switch sessions and open the session&apos;s last application..
        /// </summary>
        internal static string SESSION_EXPLORER_STR_HELP_STRING1 {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_HELP_STRING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking an application will switch sessions to that application..
        /// </summary>
        internal static string SESSION_EXPLORER_STR_HELP_STRING2 {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_HELP_STRING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care - Session Explorer.
        /// </summary>
        internal static string SESSION_EXPLORER_STR_SESSION_EXP_MSGBOX_CAPTION {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_SESSION_EXP_MSGBOX_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Call Start Time.
        /// </summary>
        internal static string SESSION_EXPLORER_STR_SORTBY_CALL_DATETIME {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_SORTBY_CALL_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Customer Name.
        /// </summary>
        internal static string SESSION_EXPLORER_STR_SORTBY_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_SORTBY_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow for this session is pending..
        /// </summary>
        internal static string SESSION_EXPLORER_STR_WORKFLOW_PENDING_MSG1 {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_WORKFLOW_PENDING_MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to complete the workflow steps before closing the session..
        /// </summary>
        internal static string SESSION_EXPLORER_STR_WORKFLOW_PENDING_MSG2 {
            get {
                return ResourceManager.GetString("SESSION_EXPLORER_STR_WORKFLOW_PENDING_MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session still has a call.
        ///
        ///Do you wish to hang it up?.
        /// </summary>
        internal static string SESSION_HAS_A_CONNECTED_CALL {
            get {
                return ResourceManager.GetString("SESSION_HAS_A_CONNECTED_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session has a held call.  You need to take the call off hold before closing the session.
        ///
        ///Do you wish to speak to the customer now?.
        /// </summary>
        internal static string SESSION_HAS_A_HELD_CALL {
            get {
                return ResourceManager.GetString("SESSION_HAS_A_HELD_CALL", resourceCulture);
            }
        }
    }
}
