//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ccf.Samples.WebchatClient.WebchatServer
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.ccf.samples.webchatserver/", ConfigurationName="Microsoft.Ccf.Samples.WebchatClient.WebchatServer.WebchatServer")]
    public interface WebchatServer
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.ccf.samples.webchatserver/WebchatServer/GetNextWebchatSessionID", ReplyAction="http://microsoft.ccf.samples.webchatserver/WebchatServer/GetNextWebchatSessionIDR" +
            "esponse")]
        int GetNextWebchatSessionID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.ccf.samples.webchatserver/WebchatServer/ReadMessage", ReplyAction="http://microsoft.ccf.samples.webchatserver/WebchatServer/ReadMessageResponse")]
        string ReadMessage(int webchatSessionID, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.ccf.samples.webchatserver/WebchatServer/SendMessage", ReplyAction="http://microsoft.ccf.samples.webchatserver/WebchatServer/SendMessageResponse")]
        int SendMessage(int webchatSessionID, int agentID, int customerID, string sender, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WebchatServerChannel : Microsoft.Ccf.Samples.WebchatClient.WebchatServer.WebchatServer, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebchatServerClient : System.ServiceModel.ClientBase<Microsoft.Ccf.Samples.WebchatClient.WebchatServer.WebchatServer>, Microsoft.Ccf.Samples.WebchatClient.WebchatServer.WebchatServer
    {
        
        public WebchatServerClient()
        {
        }
        
        public WebchatServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WebchatServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WebchatServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WebchatServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int GetNextWebchatSessionID()
        {
            return base.Channel.GetNextWebchatSessionID();
        }
        
        public string ReadMessage(int webchatSessionID, string sender)
        {
            return base.Channel.ReadMessage(webchatSessionID, sender);
        }
        
        public int SendMessage(int webchatSessionID, int agentID, int customerID, string sender, string message)
        {
            return base.Channel.SendMessage(webchatSessionID, agentID, customerID, sender, message);
        }
    }
}
